Add ability to parse font number ranges from user input (e.g. 1-3) (#18)
* Add ability to parse font number ranges from user input (e.g. 1-3)

* Fix parse range function from previous commit.

diff --git a/getnf b/getnf
--- a/getnf
+++ b/getnf
@@ -146,12 +146,36 @@ function menu {
 # call the menu funciton to list the available fonts
 menu
 
+# Parse input like 1-3
+function parse_range {
+	if ! [[ $1 =~ ^[0-9]+-[0-9]+$ ]]; then
+		echo "${RED}Invalid input format: $1. Expected format: X-Y.${RESET}"
+		return 1
+	fi
+	IFS='-' read -ra range <<<"$1"
+	range_start=${range[0]}
+	range_end=${range[1]}
+	for ((i = range_start; i <= range_end; i++)); do
+		index=$((i - 1))
+		if ((index >= 0 && index < ${#font_options[@]})); then
+			if [[ ${font_options[index]} != "Quit" ]]; then
+				selected_fonts[index]=${font_options[index]}
+			fi
+		else
+			echo "${RED}Invalid option: $i. Try again.${RESET}"
+			return 1
+		fi
+	done
+}
+
 ## Handle user input
 while true; do
-	read -p "${BLUE}Enter font number(s) (comma-separated):${RESET} " choices
-	IFS=',' read -ra selected <<<"$choices"
-	for choice in "${selected[@]}"; do
-		if ((choice >= 1 && choice <= ${#font_options[@]})); then
+	read -p "${BLUE}Enter font number(s) (e.g. 1,2,3 or 1-3 or 1,3-5):${RESET} " choices
+	for choice in $(echo $choices | tr ',' ' '); do
+		# check if they entered a range (e.g. 1-3)
+		if [[ $choice == *-* ]]; then
+			parse_range $choice || continue 2
+		elif ((choice >= 1 && choice <= ${#font_options[@]})); then
 			index=$((choice - 1))
 			if [[ ${font_options[$index]} == "Quit" ]]; then
 				echo "${GREEN}Goodbye!${reset}"
@@ -159,7 +183,7 @@ while true; do
 			fi
 			selected_fonts[$index]=${font_options[$index]}
 		else
-			echo "${RED}Invalid option: $choice. Try again.${reset}"
+			echo "${RED}Invalid option: $choice. Try again.${RESET}"
 			continue 2
 		fi
 	done
