Add ability to parse font number ranges from user input (e.g. 1-3)

diff --git a/getnf b/getnf
--- a/getnf
+++ b/getnf
@@ -146,20 +146,30 @@ function menu {
 # call the menu funciton to list the available fonts
 menu
 
+# Parse inputs like 1,2,3 or 1-3
+function parse_range {
+	IFS='-' read -a range <<<"$1"
+	for i in "${range[@]}"; do
+		if ((i >= 1 && i <= ${#font_options[@]})); then
+			selected_fonts[$((i - 1))]=${font_options[$((i - 1))]}
+		else
+			echo "${RED}Invalid option: $i. Try again.${RESET}"
+			return 1
+		fi
+	done
+}
+
 ## Handle user input
 while true; do
-	read -p "${BLUE}Enter font number(s) (comma-separated):${RESET} " choices
-	IFS=',' read -ra selected <<<"$choices"
-	for choice in "${selected[@]}"; do
-		if ((choice >= 1 && choice <= ${#font_options[@]})); then
-			index=$((choice - 1))
-			if [[ ${font_options[$index]} == "Quit" ]]; then
-				echo "${GREEN}Goodbye!${reset}"
-				exit
-			fi
-			selected_fonts[$index]=${font_options[$index]}
+	read -p "${BLUE}Enter font number(s) (e.g. 1,2,3 or 1-3 or 1,3-4,6):${RESET} " choices
+	for choice in $(echo $choices | tr ',' ' '); do
+		# check if they entered a range (e.g. 1-3)
+		if [[ $choice == *-* ]]; then
+			parse_range $choice || continue 2
+		elif ((choice >= 1 && choice <= ${#font_options[@]})); then
+			selected_fonts[$((choice - 1))]=${font_options[$((choice - 1))]}
 		else
-			echo "${RED}Invalid option: $choice. Try again.${reset}"
+			echo "${RED}Invalid option: $choice. Try again.${RESET}"
 			continue 2
 		fi
 	done
