Fix parse range function from previous commit.

diff --git a/getnf b/getnf
--- a/getnf
+++ b/getnf
@@ -146,12 +146,21 @@ function menu {
 # call the menu funciton to list the available fonts
 menu
 
-# Parse inputs like 1,2,3 or 1-3
+# Parse input like 1-3
 function parse_range {
-	IFS='-' read -a range <<<"$1"
-	for i in "${range[@]}"; do
-		if ((i >= 1 && i <= ${#font_options[@]})); then
-			selected_fonts[$((i - 1))]=${font_options[$((i - 1))]}
+	if ! [[ $1 =~ ^[0-9]+-[0-9]+$ ]]; then
+		echo "${RED}Invalid input format: $1. Expected format: X-Y.${RESET}"
+		return 1
+	fi
+	IFS='-' read -ra range <<<"$1"
+	range_start=${range[0]}
+	range_end=${range[1]}
+	for ((i = range_start; i <= range_end; i++)); do
+		index=$((i - 1))
+		if ((index >= 0 && index < ${#font_options[@]})); then
+			if [[ ${font_options[index]} != "Quit" ]]; then
+				selected_fonts[index]=${font_options[index]}
+			fi
 		else
 			echo "${RED}Invalid option: $i. Try again.${RESET}"
 			return 1
@@ -161,13 +170,18 @@ function parse_range {
 
 ## Handle user input
 while true; do
-	read -p "${BLUE}Enter font number(s) (e.g. 1,2,3 or 1-3 or 1,3-4,6):${RESET} " choices
+	read -p "${BLUE}Enter font number(s) (e.g. 1,2,3 or 1-3 or 1,3-5):${RESET} " choices
 	for choice in $(echo $choices | tr ',' ' '); do
 		# check if they entered a range (e.g. 1-3)
 		if [[ $choice == *-* ]]; then
 			parse_range $choice || continue 2
 		elif ((choice >= 1 && choice <= ${#font_options[@]})); then
-			selected_fonts[$((choice - 1))]=${font_options[$((choice - 1))]}
+			index=$((choice - 1))
+			if [[ ${font_options[$index]} == "Quit" ]]; then
+				echo "${GREEN}Goodbye!${reset}"
+				exit
+			fi
+			selected_fonts[$index]=${font_options[$index]}
 		else
 			echo "${RED}Invalid option: $choice. Try again.${RESET}"
 			continue 2
